import type { ERDEntity, ERDRelationship } from './types.js';

export const entities: ERDEntity[] = [
  {
    id: 'users', label: 'Users', tableName: 'users', category: 'core',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'name', type: 'STRING', constraints: ['NN'] },
      { name: 'username', type: 'STRING(30)', constraints: ['NN', 'UNQ', 'IDX'] },
      { name: 'email', type: 'STRING', constraints: ['NN', 'UNQ', 'IDX'] },
      { name: 'password', type: 'STRING', constraints: [] },
      { name: 'role', type: 'STRING(20)', constraints: ['NN', 'IDX'] },
      { name: 'admin_role', type: 'STRING(50)', constraints: [] },
      { name: 'membership_tier', type: 'STRING(20)', constraints: ['IDX'] },
      { name: 'balance_ars', type: 'DECIMAL(12,2)', constraints: ['NN'] },
      { name: 'referred_by', type: 'UUID', constraints: ['FK', 'IDX'], refTable: 'users' },
      { name: 'banned_by', type: 'UUID', constraints: ['FK'], refTable: 'users' },
      { name: 'referral_code', type: 'STRING(8)', constraints: ['UNQ', 'IDX'] },
      { name: 'is_verified', type: 'BOOLEAN', constraints: ['NN', 'IDX'] },
      { name: 'dni_verified', type: 'BOOLEAN', constraints: ['NN'] },
      { name: 'trust_score', type: 'INTEGER', constraints: ['NN'] },
      { name: 'rating', type: 'DECIMAL(3,2)', constraints: ['NN'] },
      { name: 'created_at', type: 'DATE', constraints: [] },
    ],
  },
  {
    id: 'jobs', label: 'Jobs', tableName: 'jobs', category: 'core',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'title', type: 'STRING(100)', constraints: ['NN'] },
      { name: 'description', type: 'TEXT', constraints: ['NN'] },
      { name: 'price', type: 'DECIMAL(12,2)', constraints: ['NN', 'IDX'] },
      { name: 'category', type: 'STRING(100)', constraints: ['NN', 'IDX'] },
      { name: 'location', type: 'STRING(255)', constraints: ['NN', 'IDX'] },
      { name: 'status', type: 'STRING(20)', constraints: ['NN', 'IDX'] },
      { name: 'client_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'doer_id', type: 'UUID', constraints: ['FK', 'IDX'], refTable: 'users' },
      { name: 'start_date', type: 'DATE', constraints: ['NN'] },
      { name: 'end_date', type: 'DATE', constraints: [] },
      { name: 'max_workers', type: 'INTEGER', constraints: ['NN'] },
      { name: 'publication_paid', type: 'BOOLEAN', constraints: ['NN', 'IDX'] },
      { name: 'created_at', type: 'DATE', constraints: [] },
    ],
  },
  {
    id: 'contracts', label: 'Contracts', tableName: 'contracts', category: 'core',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'job_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'jobs' },
      { name: 'client_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'doer_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'type', type: 'STRING(20)', constraints: ['NN'] },
      { name: 'price', type: 'DECIMAL(12,2)', constraints: ['NN'] },
      { name: 'commission', type: 'DECIMAL(12,2)', constraints: ['NN'] },
      { name: 'status', type: 'STRING(30)', constraints: ['NN', 'IDX'] },
      { name: 'payment_status', type: 'STRING(20)', constraints: ['NN', 'IDX'] },
      { name: 'escrow_status', type: 'STRING(20)', constraints: ['NN'] },
      { name: 'pairing_code', type: 'STRING(10)', constraints: ['UNQ', 'IDX'] },
      { name: 'client_confirmed', type: 'BOOLEAN', constraints: ['NN'] },
      { name: 'doer_confirmed', type: 'BOOLEAN', constraints: ['NN'] },
      { name: 'is_deleted', type: 'BOOLEAN', constraints: ['NN', 'IDX'] },
      { name: 'created_at', type: 'DATE', constraints: [] },
    ],
  },
  {
    id: 'proposals', label: 'Proposals', tableName: 'proposals', category: 'core',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'job_id', type: 'UUID', constraints: ['FK', 'IDX'], refTable: 'jobs' },
      { name: 'freelancer_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'client_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'proposed_price', type: 'DECIMAL(12,2)', constraints: ['NN'] },
      { name: 'cover_letter', type: 'TEXT', constraints: ['NN'] },
      { name: 'estimated_duration', type: 'INTEGER', constraints: ['NN'] },
      { name: 'status', type: 'STRING(20)', constraints: ['IDX'] },
      { name: 'is_counter_offer', type: 'BOOLEAN', constraints: ['IDX'] },
      { name: 'created_at', type: 'DATE', constraints: [] },
    ],
  },
  {
    id: 'payments', label: 'Payments', tableName: 'payments', category: 'payments',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'contract_id', type: 'UUID', constraints: ['FK', 'IDX'], refTable: 'contracts' },
      { name: 'payer_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'recipient_id', type: 'UUID', constraints: ['FK', 'IDX'], refTable: 'users' },
      { name: 'amount', type: 'DECIMAL(12,2)', constraints: ['NN'] },
      { name: 'currency', type: 'STRING(3)', constraints: ['NN'] },
      { name: 'status', type: 'STRING(30)', constraints: ['NN', 'IDX'] },
      { name: 'payment_type', type: 'STRING(30)', constraints: ['NN', 'IDX'] },
      { name: 'payment_method', type: 'STRING(20)', constraints: ['NN'] },
      { name: 'is_escrow', type: 'BOOLEAN', constraints: ['NN'] },
      { name: 'platform_fee', type: 'DECIMAL(12,2)', constraints: ['NN'] },
      { name: 'created_at', type: 'DATE', constraints: [] },
    ],
  },
  {
    id: 'disputes', label: 'Disputes', tableName: 'disputes', category: 'support',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'contract_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'contracts' },
      { name: 'payment_id', type: 'UUID', constraints: ['FK', 'IDX'], refTable: 'payments' },
      { name: 'initiated_by', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'assigned_to', type: 'UUID', constraints: ['FK', 'IDX'], refTable: 'users' },
      { name: 'category', type: 'STRING(50)', constraints: ['IDX'] },
      { name: 'status', type: 'STRING(30)', constraints: ['NN', 'IDX'] },
      { name: 'priority', type: 'STRING(20)', constraints: ['NN', 'IDX'] },
      { name: 'resolution_type', type: 'STRING(30)', constraints: [] },
      { name: 'created_at', type: 'DATE', constraints: [] },
    ],
  },
  {
    id: 'tickets', label: 'Tickets', tableName: 'tickets', category: 'support',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'user_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'assigned_to', type: 'UUID', constraints: ['FK', 'IDX'], refTable: 'users' },
      { name: 'contract_id', type: 'UUID', constraints: ['FK', 'IDX'], refTable: 'contracts' },
      { name: 'ticket_number', type: 'STRING', constraints: ['UNQ', 'IDX'] },
      { name: 'category', type: 'STRING(30)', constraints: ['IDX'] },
      { name: 'status', type: 'STRING(20)', constraints: ['NN', 'IDX'] },
      { name: 'priority', type: 'STRING(20)', constraints: ['NN'] },
      { name: 'subject', type: 'STRING(200)', constraints: ['NN'] },
      { name: 'created_at', type: 'DATE', constraints: [] },
    ],
  },
  {
    id: 'reviews', label: 'Reviews', tableName: 'reviews', category: 'content',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'contract_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'contracts' },
      { name: 'reviewer_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'reviewee_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'rating', type: 'DECIMAL(3,2)', constraints: ['NN'] },
      { name: 'category', type: 'STRING(30)', constraints: ['NN'] },
      { name: 'comment', type: 'TEXT', constraints: [] },
      { name: 'created_at', type: 'DATE', constraints: [] },
    ],
  },
  {
    id: 'memberships', label: 'Memberships', tableName: 'memberships', category: 'payments',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'user_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'payment_id', type: 'UUID', constraints: ['FK', 'IDX'], refTable: 'payments' },
      { name: 'tier', type: 'STRING(20)', constraints: ['NN', 'IDX'] },
      { name: 'status', type: 'STRING(20)', constraints: ['NN'] },
      { name: 'starts_at', type: 'DATE', constraints: ['NN'] },
      { name: 'expires_at', type: 'DATE', constraints: [] },
      { name: 'created_at', type: 'DATE', constraints: [] },
    ],
  },
  {
    id: 'balance_transactions', label: 'Balance Transactions', tableName: 'balance_transactions', category: 'payments',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'user_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'contract_id', type: 'UUID', constraints: ['FK', 'IDX'], refTable: 'contracts' },
      { name: 'payment_id', type: 'UUID', constraints: ['FK', 'IDX'], refTable: 'payments' },
      { name: 'type', type: 'STRING(30)', constraints: ['NN', 'IDX'] },
      { name: 'amount', type: 'DECIMAL(12,2)', constraints: ['NN'] },
      { name: 'balance_before', type: 'DECIMAL(12,2)', constraints: ['NN'] },
      { name: 'balance_after', type: 'DECIMAL(12,2)', constraints: ['NN'] },
      { name: 'created_at', type: 'DATE', constraints: [] },
    ],
  },
  {
    id: 'withdrawal_requests', label: 'Withdrawal Requests', tableName: 'withdrawal_requests', category: 'payments',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'user_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'amount', type: 'DECIMAL(12,2)', constraints: ['NN'] },
      { name: 'status', type: 'STRING(20)', constraints: ['NN', 'IDX'] },
      { name: 'cbu', type: 'STRING(22)', constraints: ['NN'] },
      { name: 'approved_by', type: 'UUID', constraints: ['FK'], refTable: 'users' },
      { name: 'created_at', type: 'DATE', constraints: [] },
    ],
  },
  {
    id: 'notifications', label: 'Notifications', tableName: 'notifications', category: 'communication',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'user_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'type', type: 'STRING(50)', constraints: ['NN', 'IDX'] },
      { name: 'title', type: 'STRING(200)', constraints: ['NN'] },
      { name: 'message', type: 'TEXT', constraints: ['NN'] },
      { name: 'read', type: 'BOOLEAN', constraints: ['NN', 'IDX'] },
      { name: 'created_at', type: 'DATE', constraints: [] },
    ],
  },
  {
    id: 'conversations', label: 'Conversations', tableName: 'conversations', category: 'communication',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'contract_id', type: 'UUID', constraints: ['FK', 'IDX'], refTable: 'contracts' },
      { name: 'job_id', type: 'UUID', constraints: ['FK', 'IDX'], refTable: 'jobs' },
      { name: 'type', type: 'STRING(20)', constraints: ['NN'] },
      { name: 'last_message_at', type: 'DATE', constraints: [] },
      { name: 'created_at', type: 'DATE', constraints: [] },
    ],
  },
  {
    id: 'chat_messages', label: 'Chat Messages', tableName: 'chat_messages', category: 'communication',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'conversation_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'conversations' },
      { name: 'sender_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'message', type: 'TEXT', constraints: ['NN'] },
      { name: 'type', type: 'STRING(20)', constraints: ['NN'] },
      { name: 'read', type: 'BOOLEAN', constraints: ['NN'] },
      { name: 'created_at', type: 'DATE', constraints: [] },
    ],
  },
  {
    id: 'referrals', label: 'Referrals', tableName: 'referrals', category: 'content',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'referrer_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'referred_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'status', type: 'STRING(20)', constraints: ['NN', 'IDX'] },
      { name: 'tier', type: 'INTEGER', constraints: ['NN'] },
      { name: 'created_at', type: 'DATE', constraints: [] },
    ],
  },
  {
    id: 'portfolio', label: 'Portfolio', tableName: 'portfolio', category: 'content',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'user_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'contract_id', type: 'UUID', constraints: ['FK', 'IDX'], refTable: 'contracts' },
      { name: 'title', type: 'STRING(200)', constraints: ['NN'] },
      { name: 'category', type: 'STRING(100)', constraints: ['IDX'] },
      { name: 'images', type: 'TEXT[]', constraints: ['NN'] },
      { name: 'created_at', type: 'DATE', constraints: [] },
    ],
  },
  {
    id: 'blog_posts', label: 'Blog Posts', tableName: 'blog_posts', category: 'content',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'author_id', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'title', type: 'STRING(200)', constraints: ['NN'] },
      { name: 'slug', type: 'STRING', constraints: ['UNQ', 'IDX'] },
      { name: 'category', type: 'STRING(50)', constraints: ['NN', 'IDX'] },
      { name: 'status', type: 'STRING(20)', constraints: ['NN', 'IDX'] },
      { name: 'published_at', type: 'DATE', constraints: [] },
      { name: 'created_at', type: 'DATE', constraints: [] },
    ],
  },
  {
    id: 'audit_logs', label: 'Audit Logs', tableName: 'audit_logs', category: 'auth',
    fields: [
      { name: 'id', type: 'UUID', constraints: ['PK'] },
      { name: 'performed_by', type: 'UUID', constraints: ['FK', 'NN', 'IDX'], refTable: 'users' },
      { name: 'admin_role', type: 'STRING(50)', constraints: ['NN'] },
      { name: 'action', type: 'STRING(100)', constraints: ['NN', 'IDX'] },
      { name: 'category', type: 'ENUM', constraints: ['NN', 'IDX'] },
      { name: 'severity', type: 'STRING(20)', constraints: ['NN'] },
      { name: 'target_model', type: 'STRING(50)', constraints: ['IDX'] },
      { name: 'target_id', type: 'UUID', constraints: ['IDX'] },
      { name: 'created_at', type: 'DATE', constraints: ['IDX'] },
    ],
  },
];

export const relationships: ERDRelationship[] = [
  // Users self-referential
  { id: 'u-referred', source: 'users', target: 'users', sourceField: 'referred_by', targetField: 'id', relationType: 'N:M', label: 'referido por' },
  // Jobs → Users
  { id: 'j-client', source: 'jobs', target: 'users', sourceField: 'client_id', targetField: 'id', relationType: '1:N', label: 'cliente' },
  { id: 'j-doer', source: 'jobs', target: 'users', sourceField: 'doer_id', targetField: 'id', relationType: '1:N', label: 'doer' },
  // Contracts → Jobs & Users
  { id: 'c-job', source: 'contracts', target: 'jobs', sourceField: 'job_id', targetField: 'id', relationType: '1:N', label: 'trabajo' },
  { id: 'c-client', source: 'contracts', target: 'users', sourceField: 'client_id', targetField: 'id', relationType: '1:N', label: 'cliente' },
  { id: 'c-doer', source: 'contracts', target: 'users', sourceField: 'doer_id', targetField: 'id', relationType: '1:N', label: 'trabajador' },
  // Proposals → Jobs & Users
  { id: 'p-job', source: 'proposals', target: 'jobs', sourceField: 'job_id', targetField: 'id', relationType: '1:N', label: 'trabajo' },
  { id: 'p-free', source: 'proposals', target: 'users', sourceField: 'freelancer_id', targetField: 'id', relationType: '1:N', label: 'freelancer' },
  // Payments → Contracts & Users
  { id: 'pay-c', source: 'payments', target: 'contracts', sourceField: 'contract_id', targetField: 'id', relationType: '1:N', label: 'contrato' },
  { id: 'pay-payer', source: 'payments', target: 'users', sourceField: 'payer_id', targetField: 'id', relationType: '1:N', label: 'pagador' },
  // Disputes
  { id: 'd-c', source: 'disputes', target: 'contracts', sourceField: 'contract_id', targetField: 'id', relationType: '1:1', label: 'contrato' },
  { id: 'd-pay', source: 'disputes', target: 'payments', sourceField: 'payment_id', targetField: 'id', relationType: '1:N', label: 'pago' },
  // Tickets
  { id: 't-u', source: 'tickets', target: 'users', sourceField: 'user_id', targetField: 'id', relationType: '1:N', label: 'usuario' },
  { id: 't-c', source: 'tickets', target: 'contracts', sourceField: 'contract_id', targetField: 'id', relationType: '1:N', label: 'contrato' },
  // Reviews
  { id: 'r-c', source: 'reviews', target: 'contracts', sourceField: 'contract_id', targetField: 'id', relationType: '1:N', label: 'contrato' },
  { id: 'r-reviewer', source: 'reviews', target: 'users', sourceField: 'reviewer_id', targetField: 'id', relationType: '1:N', label: 'revisor' },
  // Memberships
  { id: 'm-u', source: 'memberships', target: 'users', sourceField: 'user_id', targetField: 'id', relationType: '1:1', label: 'usuario' },
  { id: 'm-pay', source: 'memberships', target: 'payments', sourceField: 'payment_id', targetField: 'id', relationType: '1:N', label: 'pago' },
  // Balance Transactions
  { id: 'bt-u', source: 'balance_transactions', target: 'users', sourceField: 'user_id', targetField: 'id', relationType: '1:N', label: 'usuario' },
  { id: 'bt-c', source: 'balance_transactions', target: 'contracts', sourceField: 'contract_id', targetField: 'id', relationType: '1:N', label: 'contrato' },
  // Withdrawals
  { id: 'wr-u', source: 'withdrawal_requests', target: 'users', sourceField: 'user_id', targetField: 'id', relationType: '1:N', label: 'usuario' },
  // Notifications
  { id: 'n-u', source: 'notifications', target: 'users', sourceField: 'user_id', targetField: 'id', relationType: '1:N', label: 'usuario' },
  // Conversations
  { id: 'conv-c', source: 'conversations', target: 'contracts', sourceField: 'contract_id', targetField: 'id', relationType: '1:N', label: 'contrato' },
  { id: 'conv-j', source: 'conversations', target: 'jobs', sourceField: 'job_id', targetField: 'id', relationType: '1:N', label: 'trabajo' },
  // Chat Messages
  { id: 'msg-conv', source: 'chat_messages', target: 'conversations', sourceField: 'conversation_id', targetField: 'id', relationType: '1:N', label: 'conversación' },
  { id: 'msg-u', source: 'chat_messages', target: 'users', sourceField: 'sender_id', targetField: 'id', relationType: '1:N', label: 'remitente' },
  // Referrals
  { id: 'ref-referrer', source: 'referrals', target: 'users', sourceField: 'referrer_id', targetField: 'id', relationType: '1:N', label: 'referidor' },
  // Portfolio & Blog
  { id: 'port-u', source: 'portfolio', target: 'users', sourceField: 'user_id', targetField: 'id', relationType: '1:N', label: 'usuario' },
  { id: 'blog-u', source: 'blog_posts', target: 'users', sourceField: 'author_id', targetField: 'id', relationType: '1:N', label: 'autor' },
  // Audit Logs
  { id: 'al-u', source: 'audit_logs', target: 'users', sourceField: 'performed_by', targetField: 'id', relationType: '1:N', label: 'admin' },
];
