/**
 * cookies — English copy. Single source for web and mobile.
 *
 * Web reads it through i18next (client/i18n/index.ts merges it into the
 * `cookies` namespace); mobile imports it directly, having no i18n runtime.
 * Legal text must never differ between platforms, so it lives in one file.
 */

export const cookiesEn: Record<string, string> = {
  "metaTitle": "Cookie Policy - DOAPP",
  "metaDescription": "DOAPP cookie policy and tracking technologies",
  "back": "Back",
  "home": "Home",
  "title": "Cookie Policy",
  "lastUpdated": "Last updated: November 7, 2025",
  "s1Title": "1. What are Cookies?",
  "s1p1": "Cookies are small text files that are stored on your device when you visit a website. They are widely used to make websites work more efficiently and to provide information to the site owners.",
  "s1p2": "At DOAPP, we use cookies and similar technologies to improve your experience, provide essential features, and analyze the use of our platform.",
  "s2Title": "2. Types of Cookies We Use",
  "s2_1Title": "2.1 Strictly Necessary Cookies",
  "s2_1p": "These cookies are essential for you to navigate the platform and use its features. Without these cookies, the requested services cannot be provided.",
  "s2_1li1": "<b>Authentication:</b> Keep your session logged in while you browse",
  "s2_1li2": "<b>Security:</b> Protect against CSRF and XSS attacks",
  "s2_1li3": "<b>Load balancing:</b> Distribute traffic across servers",
  "s2_1dur": "⏱️ Duration: Session or until you close the browser",
  "s2_2Title": "2.2 Functionality Cookies",
  "s2_2p": "These cookies allow the platform to remember the choices you make to provide enhanced and more personal features.",
  "s2_2li1": "<b>Language preferences:</b> Remember your selected language (ES/EN)",
  "s2_2li2": "<b>Visual theme:</b> Save your light/dark mode preference",
  "s2_2li3": "<b>Notification settings:</b> Keep your alert preferences",
  "s2_2dur": "⏱️ Duration: Up to 1 year",
  "s2_3Title": "2.3 Performance and Analytics Cookies",
  "s2_3p": "These cookies collect information about how visitors use the platform. The information is anonymous and is used to improve how the site works.",
  "s2_3li1": "Most visited pages",
  "s2_3li2": "Time spent on the site",
  "s2_3li3": "Navigation paths",
  "s2_3li4": "Errors encountered",
  "s2_3dur": "⏱️ Duration: Up to 2 years",
  "s3Title": "3. Third-Party Cookies",
  "s3p": "Some of our services use third-party cookies to provide specific features:",
  "mpDesc": "To process payments securely. Cookies necessary for transaction processing and fraud prevention.",
  "mpLink": "MercadoPago Privacy Policy",
  "redisDesc": "For caching and improving the platform's performance. Does not collect personal information.",
  "s4Title": "4. Local Storage and Session Storage",
  "s4p": "In addition to cookies, we use the browser's local storage technologies:",
  "s4li1": "<b>Local Storage:</b> To save preferences that persist between sessions (theme, language)",
  "s4li2": "<b>Session Storage:</b> For temporary data during the current session",
  "s4li3": "<b>IndexedDB:</b> To store cache of non-sensitive data that improves performance",
  "s5Title": "5. Cookie Management",
  "s5p": "You have the right to decide whether to accept or reject cookies. You can manage cookies in several ways:",
  "s5_1Title": "5.1 Browser Settings",
  "s5_1p": "Most browsers accept cookies automatically, but you can change the settings to reject them:",
  "s5_1chrome": "<b>Chrome:</b> Settings → Privacy and security → Cookies",
  "s5_1firefox": "<b>Firefox:</b> Preferences → Privacy and security → Cookies and site data",
  "s5_1safari": "<b>Safari:</b> Preferences → Privacy → Cookies and website data",
  "s5_1edge": "<b>Edge:</b> Settings → Privacy, search and services → Cookies",
  "s5_2Title": "5.2 Clear Existing Cookies",
  "s5_2p": "You can delete all cookies stored on your device. Keep in mind that this will log you out and delete your saved preferences.",
  "s5Warning": "<b>⚠️ Important:</b> If you block or delete necessary cookies, some DOAPP features may not work correctly. For example, you won't be able to stay logged in.",
  "s6Title": "6. Specific Cookies We Use",
  "thName": "Name",
  "thPurpose": "Purpose",
  "thType": "Type",
  "thDuration": "Duration",
  "rowAccessPurpose": "JWT authentication",
  "typeNecessary": "Necessary",
  "dur7d": "7 days",
  "rowRefreshPurpose": "Session renewal",
  "dur30d": "30 days",
  "rowI18nPurpose": "Language preference",
  "typeFunctionality": "Functionality",
  "dur1y": "1 year",
  "rowThemePurpose": "Light/dark mode",
  "rowSidPurpose": "Session ID",
  "durSession": "Session",
  "s7Title": "7. Updates to this Policy",
  "s7p1": "We may update this Cookie Policy occasionally to reflect changes in the cookies we use or for operational, legal, or regulatory reasons.",
  "s7p2": "We recommend that you review this page periodically to stay informed about our use of cookies. The \"Last updated\" date at the top of the document indicates when it was last revised.",
  "s8Title": "8. More Information",
  "s8p": "If you have questions about our Cookie Policy, contact us at:",
  "emailLine": "<b>Email:</b> privacy@doapp.com",
  "supportLine": "<b>Support:</b> support@doapp.com",
  "control": "<b>Your control:</b> By using DOAPP, you accept the use of cookies as described in this policy. You can manage your cookie preferences at any time through your browser settings.",
  "linkTerms": "Terms and Conditions",
  "linkPrivacy": "Privacy Policy",
  "linkDisputes": "Dispute Resolution",
};
