/**
 * cookies — español copy. Single source for web and mobile.
 *
 * Web reads it through i18next (client/i18n/index.ts merges it into the
 * `cookies` namespace); mobile imports it directly, having no i18n runtime.
 * Legal text must never differ between platforms, so it lives in one file.
 */

export const cookiesEs: Record<string, string> = {
  "metaTitle": "Política de Cookies - DOAPP",
  "metaDescription": "Política de cookies y tecnologías de seguimiento de DOAPP",
  "back": "Volver",
  "home": "Inicio",
  "title": "Política de Cookies",
  "lastUpdated": "Última actualización: 7 de Noviembre de 2025",
  "s1Title": "1. ¿Qué son las Cookies?",
  "s1p1": "Las cookies son pequeños archivos de texto que se almacenan en tu dispositivo cuando visitas un sitio web. Se utilizan ampliamente para hacer que los sitios web funcionen de manera más eficiente y para proporcionar información a los propietarios del sitio.",
  "s1p2": "En DOAPP, utilizamos cookies y tecnologías similares para mejorar tu experiencia, proporcionar funcionalidades esenciales y analizar el uso de nuestra plataforma.",
  "s2Title": "2. Tipos de Cookies que Utilizamos",
  "s2_1Title": "2.1 Cookies Estrictamente Necesarias",
  "s2_1p": "Estas cookies son esenciales para que puedas navegar por la plataforma y utilizar sus funciones. Sin estas cookies, los servicios solicitados no pueden proporcionarse.",
  "s2_1li1": "<b>Autenticación:</b> Mantienen tu sesión iniciada mientras navegas",
  "s2_1li2": "<b>Seguridad:</b> Protegen contra ataques CSRF y XSS",
  "s2_1li3": "<b>Balance de carga:</b> Distribuyen el tráfico entre servidores",
  "s2_1dur": "⏱️ Duración: Sesión o hasta que cierres el navegador",
  "s2_2Title": "2.2 Cookies de Funcionalidad",
  "s2_2p": "Estas cookies permiten que la plataforma recuerde las elecciones que haces para proporcionar funcionalidades mejoradas y más personales.",
  "s2_2li1": "<b>Preferencias de idioma:</b> Recuerdan tu idioma seleccionado (ES/EN)",
  "s2_2li2": "<b>Tema visual:</b> Guardan tu preferencia de modo claro/oscuro",
  "s2_2li3": "<b>Configuración de notificaciones:</b> Mantienen tus preferencias de alertas",
  "s2_2dur": "⏱️ Duración: Hasta 1 año",
  "s2_3Title": "2.3 Cookies de Rendimiento y Análisis",
  "s2_3p": "Estas cookies recopilan información sobre cómo los visitantes utilizan la plataforma. La información es anónima y se utiliza para mejorar el funcionamiento del sitio.",
  "s2_3li1": "Páginas más visitadas",
  "s2_3li2": "Tiempo de permanencia en el sitio",
  "s2_3li3": "Rutas de navegación",
  "s2_3li4": "Errores encontrados",
  "s2_3dur": "⏱️ Duración: Hasta 2 años",
  "s3Title": "3. Cookies de Terceros",
  "s3p": "Algunos de nuestros servicios utilizan cookies de terceros para proporcionar funcionalidades específicas:",
  "mpDesc": "Para procesar pagos de manera segura. Cookies necesarias para el procesamiento de transacciones y prevención de fraudes.",
  "mpLink": "Política de Privacidad de MercadoPago",
  "redisDesc": "Para almacenamiento en caché y mejorar el rendimiento de la plataforma. No recopila información personal.",
  "s4Title": "4. Local Storage y Session Storage",
  "s4p": "Además de cookies, utilizamos tecnologías de almacenamiento local del navegador:",
  "s4li1": "<b>Local Storage:</b> Para guardar preferencias que persisten entre sesiones (tema, idioma)",
  "s4li2": "<b>Session Storage:</b> Para datos temporales durante la sesión actual",
  "s4li3": "<b>IndexedDB:</b> Para almacenar caché de datos no sensibles que mejoran el rendimiento",
  "s5Title": "5. Gestión de Cookies",
  "s5p": "Tienes el derecho de decidir si aceptas o rechazas cookies. Puedes gestionar las cookies de varias maneras:",
  "s5_1Title": "5.1 Configuración del Navegador",
  "s5_1p": "La mayoría de los navegadores aceptan cookies automáticamente, pero puedes modificar la configuración para rechazarlas:",
  "s5_1chrome": "<b>Chrome:</b> Configuración → Privacidad y seguridad → Cookies",
  "s5_1firefox": "<b>Firefox:</b> Preferencias → Privacidad y seguridad → Cookies y datos del sitio",
  "s5_1safari": "<b>Safari:</b> Preferencias → Privacidad → Cookies y datos de sitios web",
  "s5_1edge": "<b>Edge:</b> Configuración → Privacidad, búsqueda y servicios → Cookies",
  "s5_2Title": "5.2 Limpiar Cookies Existentes",
  "s5_2p": "Puedes eliminar todas las cookies almacenadas en tu dispositivo. Ten en cuenta que esto cerrará tu sesión y eliminará tus preferencias guardadas.",
  "s5Warning": "<b>⚠️ Importante:</b> Si bloqueas o eliminas las cookies necesarias, algunas funcionalidades de DOAPP pueden no funcionar correctamente. Por ejemplo, no podrás mantener tu sesión iniciada.",
  "s6Title": "6. Cookies Específicas que Usamos",
  "thName": "Nombre",
  "thPurpose": "Propósito",
  "thType": "Tipo",
  "thDuration": "Duración",
  "rowAccessPurpose": "Autenticación JWT",
  "typeNecessary": "Necesaria",
  "dur7d": "7 días",
  "rowRefreshPurpose": "Renovación de sesión",
  "dur30d": "30 días",
  "rowI18nPurpose": "Preferencia de idioma",
  "typeFunctionality": "Funcionalidad",
  "dur1y": "1 año",
  "rowThemePurpose": "Modo claro/oscuro",
  "rowSidPurpose": "ID de sesión",
  "durSession": "Sesión",
  "s7Title": "7. Actualizaciones de esta Política",
  "s7p1": "Podemos actualizar esta Política de Cookies ocasionalmente para reflejar cambios en las cookies que utilizamos o por razones operativas, legales o regulatorias.",
  "s7p2": "Te recomendamos que revises esta página periódicamente para estar informado sobre nuestro uso de cookies. La fecha de \"Última actualización\" al inicio del documento indica cuándo se revisó por última vez.",
  "s8Title": "8. Más Información",
  "s8p": "Si tienes preguntas sobre nuestra Política de Cookies, contáctanos en:",
  "emailLine": "<b>Email:</b> privacy@doapp.com",
  "supportLine": "<b>Soporte:</b> support@doapp.com",
  "control": "<b>Tu control:</b> Al utilizar DOAPP, aceptas el uso de cookies según se describe en esta política. Puedes gestionar tus preferencias de cookies en cualquier momento a través de la configuración de tu navegador.",
  "linkTerms": "Términos y Condiciones",
  "linkPrivacy": "Política de Privacidad",
  "linkDisputes": "Resolución de Disputas",
};
