/**
 * disputeRes — español copy. Single source for web and mobile.
 *
 * Web reads it through i18next (client/i18n/index.ts merges it into the
 * `disputeRes` namespace); mobile imports it directly, having no i18n runtime.
 * Legal text must never differ between platforms, so it lives in one file.
 */

export const disputesEs: Record<string, string> = {
  "metaTitle": "Resolución de Disputas - DOAPP",
  "metaDescription": "Proceso de resolución de disputas y mediación de DOAPP",
  "back": "Volver",
  "home": "Inicio",
  "title": "Resolución de Disputas",
  "lastUpdated": "Última actualización: 7 de Noviembre de 2025",
  "s1Title": "1. Introducción",
  "s1p1": "En DOAPP, nos esforzamos por proporcionar un ambiente seguro y justo para todas las transacciones. Sin embargo, entendemos que pueden surgir desacuerdos entre las personas dentro de la app. Este documento establece el proceso formal de resolución de disputas.",
  "s1p2": "Nuestro objetivo es resolver todos los conflictos de manera justa, transparente y eficiente, protegiendo los intereses de ambas partes.",
  "s2Title": "2. ¿Cuándo Iniciar una Disputa?",
  "s2p": "Debes considerar iniciar una disputa en las siguientes situaciones:",
  "s2ClientsTitle": "Para Clientes:",
  "s2c1": "El trabajo entregado no coincide con lo acordado en los detalles",
  "s2c2": "El Doer no completó el trabajo según las especificaciones",
  "s2c3": "El Doer incumplió los plazos sin justificación válida",
  "s2c4": "La calidad del trabajo es significativamente inferior a lo esperado",
  "s2c5": "El Doer no responde a comunicaciones durante un período prolongado",
  "s2WorkersTitle": "Para Profesionales:",
  "s2w1": "El cliente no aprueba el trabajo completado sin motivo válido",
  "s2w2": "El cliente solicita cambios no incluidos en el acuerdo original",
  "s2w3": "El cliente no proporciona información necesaria para completar el trabajo",
  "s2w4": "El cliente rechaza injustificadamente el trabajo entregado correctamente",
  "s2tip": "<b>💡 Recomendación:</b> Antes de iniciar una disputa formal, te recomendamos intentar resolver el problema directamente con la otra parte a través de la mensajería de la plataforma. Muchos conflictos se resuelven mediante comunicación directa.",
  "s3Title": "3. Proceso de Resolución de Disputas",
  "step1Title": "Paso 1: Apertura de Disputa",
  "step1p": "Cualquier parte puede iniciar una disputa desde la página del contrato haciendo clic en \"Abrir Disputa\". Deberás proporcionar:",
  "step1li1": "Descripción detallada del problema",
  "step1li2": "Evidencia relevante (capturas de pantalla, mensajes, archivos)",
  "step1li3": "Resultado deseado",
  "step1note": "⏱️ Los fondos del contrato se congelan automáticamente hasta resolver la disputa",
  "step2Title": "Paso 2: Notificación y Respuesta",
  "step2p": "La otra parte es notificada y tiene <b>48 horas</b> para responder con:",
  "step2li1": "Su versión de los hechos",
  "step2li2": "Evidencia que respalde su posición",
  "step2li3": "Propuesta de solución (opcional)",
  "step3Title": "Paso 3: Revisión del Equipo de DOAPP",
  "step3p": "Nuestro equipo de mediación revisa toda la evidencia presentada:",
  "step3li1": "Mensajes intercambiados en la plataforma",
  "step3li2": "Archivos y entregables",
  "step3li3": "Términos acordados en el contrato",
  "step3li4": "Historial de comportamiento de ambas partes",
  "step3note": "⏱️ Tiempo de revisión: 3-5 días hábiles",
  "step4Title": "Paso 4: Resolución",
  "step4p": "El equipo de DOAPP emite una decisión que puede incluir:",
  "step4li1": "<b>Liberación total:</b> El pago completo se libera al Doer",
  "step4li2": "<b>Reembolso total:</b> El monto completo se devuelve al cliente",
  "step4li3": "<b>Reembolso parcial:</b> Se divide el pago según corresponda",
  "step4li4": "<b>Extensión de plazo:</b> Se otorga más tiempo para completar el trabajo",
  "s4Title": "4. Evidencia Requerida",
  "s4p": "Para una resolución justa, es importante proporcionar evidencia clara. Ejemplos de evidencia válida:",
  "acceptableTitle": "✅ Evidencia Aceptable",
  "acc1": "• Capturas de pantalla de conversaciones",
  "acc2": "• Archivos entregables",
  "acc3": "• Registros de cambios solicitados",
  "acc4": "• Especificaciones del proyecto",
  "acc5": "• Emails o mensajes relevantes",
  "acc6": "• Comprobantes de entrega",
  "invalidTitle": "❌ Evidencia No Válida",
  "inv1": "• Comunicaciones fuera de la plataforma sin verificar",
  "inv2": "• Capturas modificadas o editadas",
  "inv3": "• Testimonios de terceros no verificables",
  "inv4": "• Suposiciones sin respaldo",
  "inv5": "• Evidencia irrelevante al caso",
  "s4warning": "<b>⚠️ Importante:</b> Toda la comunicación relacionada con el contrato debe realizarse a través de la plataforma DOAPP. Las comunicaciones fuera de la plataforma no pueden ser verificadas y tendrán menos peso en la resolución.",
  "s5Title": "5. Criterios de Decisión",
  "s5p": "Nuestro equipo basa sus decisiones en los siguientes criterios:",
  "s5li1": "<b>Términos del contrato:</b> Cumplimiento de lo acordado originalmente",
  "s5li2": "<b>Calidad del trabajo:</b> Si cumple con estándares profesionales razonables",
  "s5li3": "<b>Comunicación:</b> Actitud colaborativa y profesional de ambas partes",
  "s5li4": "<b>Plazos:</b> Cumplimiento de fechas acordadas",
  "s5li5": "<b>Cambios solicitados:</b> Si estaban incluidos en el acuerdo original",
  "s5li6": "<b>Historial:</b> Comportamiento previo de las partes en la plataforma",
  "s6Title": "6. Apelaciones",
  "s6p": "Si no estás de acuerdo con la decisión inicial, puedes solicitar una apelación dentro de las <b>72 horas</b> posteriores a la resolución. Para apelar, debes:",
  "s6li1": "Proporcionar evidencia nueva no presentada anteriormente",
  "s6li2": "Explicar claramente por qué consideras que la decisión fue incorrecta",
  "s6li3": "Presentar argumentos sólidos y documentados",
  "s6note": "Un miembro diferente del equipo revisará la apelación. La decisión de la apelación es final e inapelable.",
  "s7Title": "7. Consecuencias de Disputas Frecuentes",
  "s7p": "Los usuarios con múltiples disputas pueden enfrentar:",
  "s7li1": "<b>Primera disputa perdida:</b> Advertencia en el perfil",
  "s7li2": "<b>Segunda disputa perdida:</b> Suspensión temporal (7-30 días)",
  "s7li3": "<b>Tercera disputa perdida:</b> Revisión completa de la cuenta",
  "s7li4": "<b>Patrón de mal comportamiento:</b> Suspensión permanente",
  "fraudLabel": "Fraude:",
  "fraudText": "Iniciar disputas falsas o malintencionadas resultará en la suspensión inmediata de la cuenta y posibles acciones legales.",
  "s8Title": "8. Prevención de Disputas",
  "s8p": "Para minimizar la posibilidad de disputas, recomendamos:",
  "s8ClientsTitle": "Para Clientes:",
  "s8c1": "✓ Describe claramente lo que necesitas",
  "s8c2": "✓ Proporciona ejemplos y referencias",
  "s8c3": "✓ Establece plazos realistas",
  "s8c4": "✓ Mantén comunicación regular",
  "s8c5": "✓ Revisa el progreso periódicamente",
  "s8c6": "✓ Proporciona feedback constructivo",
  "s8WorkersTitle": "Para Profesionales:",
  "s8w1": "✓ Aclara todos los requisitos antes de empezar",
  "s8w2": "✓ Comunica el progreso regularmente",
  "s8w3": "✓ Entrega según lo acordado",
  "s8w4": "✓ Avisa inmediatamente de cualquier problema",
  "s8w5": "✓ Documenta cambios solicitados",
  "s8w6": "✓ Mantén profesionalismo siempre",
  "s9Title": "9. Mediación Alternativa",
  "s9p": "En casos complejos, DOAPP puede sugerir mediación adicional antes de emitir una decisión final. Esto puede incluir:",
  "s9li1": "Videoconferencia con ambas partes y un mediador",
  "s9li2": "Período de negociación asistida",
  "s9li3": "Revisión técnica por expertos externos (en casos específicos)",
  "s10Title": "10. Contacto para Disputas",
  "s10p": "Para iniciar una disputa o consultas sobre el proceso:",
  "s10li1": "<b>Desde la plataforma:</b> Botón &quot;Abrir Disputa&quot; en la página del contrato",
  "s10li2": "<b>Email:</b> disputes@doapp.com",
  "s10li3": "<b>Soporte:</b> Centro de ayuda en la plataforma",
  "commitment": "<b>Compromiso de DOAPP:</b> Nos comprometemos a resolver todas las disputas de manera justa, imparcial y transparente. Nuestro objetivo es proteger los intereses legítimos de ambas partes y mantener la confianza en nuestra plataforma.",
  "remember": "Recuerda: La mejor disputa es la que se evita mediante buena comunicación y profesionalismo.",
  "linkTerms": "Términos y Condiciones",
  "linkPrivacy": "Política de Privacidad",
  "linkCookies": "Política de Cookies",
};
