/**
 * disputeRes — English copy. Single source for web and mobile.
 *
 * Web reads it through i18next (client/i18n/index.ts merges it into the
 * `disputeRes` namespace); mobile imports it directly, having no i18n runtime.
 * Legal text must never differ between platforms, so it lives in one file.
 */

export const disputesEn: Record<string, string> = {
  "metaTitle": "Dispute Resolution - DOAPP",
  "metaDescription": "DOAPP dispute resolution and mediation process",
  "back": "Back",
  "home": "Home",
  "title": "Dispute Resolution",
  "lastUpdated": "Last updated: November 7, 2025",
  "s1Title": "1. Introduction",
  "s1p1": "At DOAPP, we strive to provide a safe and fair environment for all transactions. However, we understand that disagreements can arise between people within the app. This document sets out the formal dispute resolution process.",
  "s1p2": "Our goal is to resolve all conflicts fairly, transparently, and efficiently, protecting the interests of both parties.",
  "s2Title": "2. When to Start a Dispute?",
  "s2p": "You should consider starting a dispute in the following situations:",
  "s2ClientsTitle": "For Clients:",
  "s2c1": "The delivered work does not match what was agreed in the details",
  "s2c2": "The Doer did not complete the work according to the specifications",
  "s2c3": "The Doer missed the deadlines without valid justification",
  "s2c4": "The quality of the work is significantly lower than expected",
  "s2c5": "The Doer does not respond to communications for an extended period",
  "s2WorkersTitle": "For Professionals:",
  "s2w1": "The client does not approve the completed work without a valid reason",
  "s2w2": "The client requests changes not included in the original agreement",
  "s2w3": "The client does not provide information needed to complete the work",
  "s2w4": "The client unjustifiably rejects work that was delivered correctly",
  "s2tip": "<b>💡 Recommendation:</b> Before starting a formal dispute, we recommend trying to resolve the problem directly with the other party through the platform's messaging. Many conflicts are resolved through direct communication.",
  "s3Title": "3. Dispute Resolution Process",
  "step1Title": "Step 1: Opening a Dispute",
  "step1p": "Either party can start a dispute from the contract page by clicking \"Open Dispute\". You will need to provide:",
  "step1li1": "Detailed description of the problem",
  "step1li2": "Relevant evidence (screenshots, messages, files)",
  "step1li3": "Desired outcome",
  "step1note": "⏱️ The contract funds are automatically frozen until the dispute is resolved",
  "step2Title": "Step 2: Notification and Response",
  "step2p": "The other party is notified and has <b>48 hours</b> to respond with:",
  "step2li1": "Their version of the facts",
  "step2li2": "Evidence supporting their position",
  "step2li3": "Proposed solution (optional)",
  "step3Title": "Step 3: DOAPP Team Review",
  "step3p": "Our mediation team reviews all the evidence presented:",
  "step3li1": "Messages exchanged on the platform",
  "step3li2": "Files and deliverables",
  "step3li3": "Terms agreed in the contract",
  "step3li4": "Behavior history of both parties",
  "step3note": "⏱️ Review time: 3-5 business days",
  "step4Title": "Step 4: Resolution",
  "step4p": "The DOAPP team issues a decision that may include:",
  "step4li1": "<b>Full release:</b> The full payment is released to the Doer",
  "step4li2": "<b>Full refund:</b> The full amount is returned to the client",
  "step4li3": "<b>Partial refund:</b> The payment is split as appropriate",
  "step4li4": "<b>Deadline extension:</b> More time is granted to complete the work",
  "s4Title": "4. Required Evidence",
  "s4p": "For a fair resolution, it is important to provide clear evidence. Examples of valid evidence:",
  "acceptableTitle": "✅ Acceptable Evidence",
  "acc1": "• Screenshots of conversations",
  "acc2": "• Deliverable files",
  "acc3": "• Records of requested changes",
  "acc4": "• Project specifications",
  "acc5": "• Relevant emails or messages",
  "acc6": "• Proof of delivery",
  "invalidTitle": "❌ Invalid Evidence",
  "inv1": "• Unverified off-platform communications",
  "inv2": "• Modified or edited screenshots",
  "inv3": "• Unverifiable third-party testimony",
  "inv4": "• Unsupported assumptions",
  "inv5": "• Evidence irrelevant to the case",
  "s4warning": "<b>⚠️ Important:</b> All communication related to the contract must take place through the DOAPP platform. Off-platform communications cannot be verified and will carry less weight in the resolution.",
  "s5Title": "5. Decision Criteria",
  "s5p": "Our team bases its decisions on the following criteria:",
  "s5li1": "<b>Contract terms:</b> Compliance with what was originally agreed",
  "s5li2": "<b>Work quality:</b> Whether it meets reasonable professional standards",
  "s5li3": "<b>Communication:</b> Collaborative and professional attitude of both parties",
  "s5li4": "<b>Deadlines:</b> Compliance with agreed dates",
  "s5li5": "<b>Requested changes:</b> Whether they were included in the original agreement",
  "s5li6": "<b>History:</b> Previous behavior of the parties on the platform",
  "s6Title": "6. Appeals",
  "s6p": "If you disagree with the initial decision, you can request an appeal within <b>72 hours</b> of the resolution. To appeal, you must:",
  "s6li1": "Provide new evidence not previously submitted",
  "s6li2": "Clearly explain why you believe the decision was incorrect",
  "s6li3": "Present solid, documented arguments",
  "s6note": "A different team member will review the appeal. The appeal decision is final and cannot be appealed.",
  "s7Title": "7. Consequences of Frequent Disputes",
  "s7p": "Users with multiple disputes may face:",
  "s7li1": "<b>First lost dispute:</b> Warning on the profile",
  "s7li2": "<b>Second lost dispute:</b> Temporary suspension (7-30 days)",
  "s7li3": "<b>Third lost dispute:</b> Full account review",
  "s7li4": "<b>Pattern of misconduct:</b> Permanent suspension",
  "fraudLabel": "Fraud:",
  "fraudText": "Starting false or malicious disputes will result in immediate account suspension and possible legal action.",
  "s8Title": "8. Dispute Prevention",
  "s8p": "To minimize the possibility of disputes, we recommend:",
  "s8ClientsTitle": "For Clients:",
  "s8c1": "✓ Clearly describe what you need",
  "s8c2": "✓ Provide examples and references",
  "s8c3": "✓ Set realistic deadlines",
  "s8c4": "✓ Keep regular communication",
  "s8c5": "✓ Review progress periodically",
  "s8c6": "✓ Provide constructive feedback",
  "s8WorkersTitle": "For Professionals:",
  "s8w1": "✓ Clarify all requirements before starting",
  "s8w2": "✓ Communicate progress regularly",
  "s8w3": "✓ Deliver as agreed",
  "s8w4": "✓ Report any problem immediately",
  "s8w5": "✓ Document requested changes",
  "s8w6": "✓ Always maintain professionalism",
  "s9Title": "9. Alternative Mediation",
  "s9p": "In complex cases, DOAPP may suggest additional mediation before issuing a final decision. This may include:",
  "s9li1": "Video call with both parties and a mediator",
  "s9li2": "Assisted negotiation period",
  "s9li3": "Technical review by external experts (in specific cases)",
  "s10Title": "10. Contact for Disputes",
  "s10p": "To start a dispute or for questions about the process:",
  "s10li1": "<b>From the platform:</b> \"Open Dispute\" button on the contract page",
  "s10li2": "<b>Email:</b> disputes@doapp.com",
  "s10li3": "<b>Support:</b> Help center on the platform",
  "commitment": "<b>DOAPP's commitment:</b> We are committed to resolving all disputes fairly, impartially, and transparently. Our goal is to protect the legitimate interests of both parties and maintain trust in our platform.",
  "remember": "Remember: The best dispute is the one avoided through good communication and professionalism.",
  "linkTerms": "Terms and Conditions",
  "linkPrivacy": "Privacy Policy",
  "linkCookies": "Cookie Policy",
};
