/**
 * privacy — English copy. Single source for web and mobile.
 *
 * Web reads it through i18next (client/i18n/index.ts merges it into the
 * `privacy` namespace); mobile imports it directly, having no i18n runtime.
 * Legal text must never differ between platforms, so it lives in one file.
 */

export const privacyEn: Record<string, string> = {
  "metaTitle": "Privacy Policy - DOAPP",
  "metaDescription": "DOAPP privacy policy and data protection",
  "back": "Back",
  "home": "Home",
  "title": "Privacy Policy",
  "lastUpdated": "Last updated: November 7, 2025",
  "s1Title": "1. Information We Collect",
  "s1p": "At DOAPP, we collect different types of information to provide you with a better service:",
  "s1_1Title": "1.1 Registration Information",
  "s1_1li1": "Full name and contact details",
  "s1_1li2": "Email address and phone number",
  "s1_1li3": "Professional profile information",
  "s1_1li4": "Profile photo (optional)",
  "s1_2Title": "1.2 Financial Information",
  "s1_2li1": "Bank details for transfers (CBU/CVU)",
  "s1_2li2": "Payment information processed through MercadoPago",
  "s1_2li3": "Transaction history on the platform",
  "s1_3Title": "1.3 Usage Information",
  "s1_3li1": "Contracts published and completed",
  "s1_3li2": "Messages and communications on the platform",
  "s1_3li3": "Ratings and reviews",
  "s1_3li4": "Browsing activity and preferences",
  "s2Title": "2. How We Use Your Information",
  "s2p": "We use the collected information to:",
  "s2li1": "Provide and improve our services",
  "s2li2": "Process payments and transactions securely",
  "s2li3": "Verify users' identity",
  "s2li4": "Detect and prevent fraud",
  "s2li5": "Send important notifications about your account",
  "s2li6": "Personalize your experience on the platform",
  "s2li7": "Comply with legal and regulatory obligations",
  "s3Title": "3. Sharing Information",
  "s3p": "We do not sell your personal information. We share information only in the following cases:",
  "s3li1": "<b>With other users:</b> Your public profile, ratings, and portfolio are visible to other users",
  "s3li2": "<b>Service providers:</b> MercadoPago for payment processing, email services, etc.",
  "s3li5": "<b>Identity verification:</b> Didit (didit.me) acts as data processor to verify your identity. We transmit the images of your document and your face, together with the derived biometric data needed for the liveness check, for the sole purpose of confirming that it is you and preventing fraud. We do not use that data for any other purpose, nor do we transfer it to third parties.",
  "s3li3": "<b>Legal compliance:</b> When required by law or to protect our rights",
  "s3li4": "<b>Business transfers:</b> In the event of a merger, sale, or reorganization",
  "s3intlTitle": "International data transfers",
  "s3intl": "Some of the providers listed above process and store information outside the Argentine Republic. In particular, identity verification and the associated images are processed by Didit on servers located abroad. In accordance with article 12 of Personal Data Protection Act No. 25,326, by starting identity verification you give your express consent to that international transfer, which is carried out solely for the purpose described and under contractual confidentiality and security obligations. You may withdraw your consent at any time by contacting us, bearing in mind that without identity verification it is not possible to operate on the Platform.",
  "s4Title": "4. Data Security",
  "s4p": "We implement security measures to protect your information:",
  "s4li1": "Encryption of sensitive data (passwords, banking information)",
  "s4li2": "Two-factor authentication (2FA) available",
  "s4li3": "Secure connections via HTTPS/SSL",
  "s4li4": "Continuous security monitoring",
  "s4li5": "Restricted access to personal information",
  "s5Title": "5. Your Rights",
  "s5p": "In accordance with Argentina's Personal Data Protection Law (Law 25.326), you have the right to:",
  "s5li1": "<b>Access:</b> Request a copy of your personal information",
  "s5li2": "<b>Rectification:</b> Correct inaccurate or incomplete information",
  "s5li3": "<b>Deletion:</b> Request the deletion of your information (subject to legal limitations)",
  "s5li4": "<b>Objection:</b> Object to the processing of your data for certain purposes",
  "s5li5": "<b>Portability:</b> Receive your data in a structured, transferable format",
  "s5contact": "To exercise these rights, contact us at privacy@doapp.com",
  "s6Title": "6. Cookies and Similar Technologies",
  "s6p": "We use cookies and similar technologies to:",
  "s6li1": "Keep your session logged in",
  "s6li2": "Remember your preferences (language, theme)",
  "s6li3": "Analyze the use of the platform",
  "s6li4": "Improve the site's performance",
  "s6more": "For more information, see our <lnk>Cookie Policy</lnk>.",
  "s7Title": "7. Data Retention",
  "s7p": "We keep your personal information while:",
  "s7li1": "Your account is active",
  "s7li2": "It is necessary to provide services",
  "s7li3": "We have legal obligations to retain it",
  "s7li4": "It is necessary to resolve disputes",
  "s7note": "After deleting your account, we will retain certain information as required by law (accounting records, transaction history for audits).",
  "s8Title": "8. Minors",
  "s8p": "DOAPP is not directed at people under 18 years of age. We do not intentionally collect information from minors. If we discover that we have collected information from a minor, we will delete it immediately.",
  "s9Title": "9. Changes to this Policy",
  "s9p": "We may update this policy periodically. We will notify you of significant changes through:",
  "s9li1": "A prominent notice on the platform",
  "s9li2": "Email notification",
  "s9li3": "Updating the \"Last updated\" date at the top of this document",
  "s10Title": "10. Contact",
  "s10p": "For questions about this privacy policy or the handling of your data:",
  "emailLine": "<b>Email:</b> privacy@doapp.com",
  "dpoLine": "<b>Data Protection Officer:</b> dpo@doapp.com",
  "addressLine": "<b>Address:</b> Buenos Aires, Argentina",
  "s10note": "You may also file a complaint with Argentina's Agency for Access to Public Information (AAIP).",
  "commitment": "<b>Privacy commitment:</b> At DOAPP we value your privacy and are committed to protecting your personal information. If you have any questions or concerns, don't hesitate to contact us.",
  "linkTerms": "Terms and Conditions",
  "linkCookies": "Cookie Policy",
  "linkDisputes": "Dispute Resolution",
};
