/**
 * privacy — español copy. Single source for web and mobile.
 *
 * Web reads it through i18next (client/i18n/index.ts merges it into the
 * `privacy` namespace); mobile imports it directly, having no i18n runtime.
 * Legal text must never differ between platforms, so it lives in one file.
 */

export const privacyEs: Record<string, string> = {
  "metaTitle": "Política de Privacidad - DOAPP",
  "metaDescription": "Política de privacidad y protección de datos de DOAPP",
  "back": "Volver",
  "home": "Inicio",
  "title": "Política de Privacidad",
  "lastUpdated": "Última actualización: 7 de Noviembre de 2025",
  "s1Title": "1. Información que Recopilamos",
  "s1p": "En DOAPP, recopilamos diferentes tipos de información para brindarte un mejor servicio:",
  "s1_1Title": "1.1 Información de Registro",
  "s1_1li1": "Nombre completo y datos de contacto",
  "s1_1li2": "Correo electrónico y número de teléfono",
  "s1_1li3": "Información de perfil profesional",
  "s1_1li4": "Fotografía de perfil (opcional)",
  "s1_2Title": "1.2 Información Financiera",
  "s1_2li1": "Datos bancarios para transferencias (CBU/CVU)",
  "s1_2li2": "Información de pagos procesada a través de MercadoPago",
  "s1_2li3": "Historial de transacciones en la plataforma",
  "s1_3Title": "1.3 Información de Uso",
  "s1_3li1": "Contratos publicados y completados",
  "s1_3li2": "Mensajes y comunicaciones en la plataforma",
  "s1_3li3": "Calificaciones y reseñas",
  "s1_3li4": "Actividad de navegación y preferencias",
  "s2Title": "2. Cómo Utilizamos tu Información",
  "s2p": "Utilizamos la información recopilada para:",
  "s2li1": "Proporcionar y mejorar nuestros servicios",
  "s2li2": "Procesar pagos y transacciones de manera segura",
  "s2li3": "Verificar la identidad de los usuarios",
  "s2li4": "Detectar y prevenir fraudes",
  "s2li5": "Enviar notificaciones importantes sobre tu cuenta",
  "s2li6": "Personalizar tu experiencia en la plataforma",
  "s2li7": "Cumplir con obligaciones legales y regulatorias",
  "s3Title": "3. Compartir Información",
  "s3p": "No vendemos tu información personal. Compartimos información solo en los siguientes casos:",
  "s3li1": "<b>Con otros usuarios:</b> Tu perfil público, calificaciones y portfolio son visibles para otros usuarios",
  "s3li2": "<b>Proveedores de servicios:</b> MercadoPago para procesamiento de pagos, servicios de email, etc.",
  "s3li5": "<b>Verificación de identidad:</b> Didit (didit.me) actúa como encargado del tratamiento para verificar tu identidad. Le transmitimos las imágenes de tu documento y de tu rostro, junto con los datos biométricos derivados necesarios para la prueba de vida, con la única finalidad de comprobar que sos vos y prevenir el fraude. No utilizamos esos datos para ningún otro fin ni los cedemos a terceros.",
  "s3li3": "<b>Cumplimiento legal:</b> Cuando sea requerido por ley o para proteger nuestros derechos",
  "s3li4": "<b>Transferencias empresariales:</b> En caso de fusión, venta o reorganización",
  "s3intlTitle": "Transferencia internacional de datos",
  "s3intl": "Algunos de los proveedores mencionados procesan y almacenan información fuera de la República Argentina. En particular, la verificación de identidad y las imágenes asociadas son tratadas por Didit en servidores ubicados en el exterior. Conforme al artículo 12 de la Ley 25.326 de Protección de los Datos Personales, al iniciar la verificación de identidad prestás tu consentimiento expreso para dicha transferencia internacional, que se realiza únicamente con la finalidad descripta y bajo obligaciones contractuales de confidencialidad y seguridad. Podés revocar tu consentimiento en cualquier momento escribiéndonos, teniendo en cuenta que sin verificación de identidad no es posible operar en la Plataforma.",
  "s4Title": "4. Seguridad de Datos",
  "s4p": "Implementamos medidas de seguridad para proteger tu información:",
  "s4li1": "Cifrado de datos sensibles (contraseñas, información bancaria)",
  "s4li2": "Autenticación de dos factores (2FA) disponible",
  "s4li3": "Conexiones seguras mediante HTTPS/SSL",
  "s4li4": "Monitoreo continuo de seguridad",
  "s4li5": "Acceso restringido a información personal",
  "s5Title": "5. Tus Derechos",
  "s5p": "Conforme a la Ley de Protección de Datos Personales de Argentina (Ley 25.326), tienes derecho a:",
  "s5li1": "<b>Acceso:</b> Solicitar una copia de tu información personal",
  "s5li2": "<b>Rectificación:</b> Corregir información inexacta o incompleta",
  "s5li3": "<b>Supresión:</b> Solicitar la eliminación de tu información (sujeto a limitaciones legales)",
  "s5li4": "<b>Oposición:</b> Oponerte al procesamiento de tus datos para ciertos fines",
  "s5li5": "<b>Portabilidad:</b> Recibir tus datos en un formato estructurado y transferible",
  "s5contact": "Para ejercer estos derechos, contáctanos en privacy@doapp.com",
  "s6Title": "6. Cookies y Tecnologías Similares",
  "s6p": "Utilizamos cookies y tecnologías similares para:",
  "s6li1": "Mantener tu sesión iniciada",
  "s6li2": "Recordar tus preferencias (idioma, tema)",
  "s6li3": "Analizar el uso de la plataforma",
  "s6li4": "Mejorar el rendimiento del sitio",
  "s6more": "Para más información, consulta nuestra <lnk>Política de Cookies</lnk>.",
  "s7Title": "7. Retención de Datos",
  "s7p": "Conservamos tu información personal mientras:",
  "s7li1": "Tu cuenta esté activa",
  "s7li2": "Sea necesaria para proporcionar servicios",
  "s7li3": "Tengamos obligaciones legales de conservarla",
  "s7li4": "Sea necesaria para resolver disputas",
  "s7note": "Tras eliminar tu cuenta, conservaremos cierta información según lo requiera la ley (registros contables, historial de transacciones para auditorías).",
  "s8Title": "8. Menores de Edad",
  "s8p": "DOAPP no está dirigida a menores de 18 años. No recopilamos intencionalmente información de menores. Si descubrimos que hemos recopilado información de un menor, la eliminaremos inmediatamente.",
  "s9Title": "9. Cambios a esta Política",
  "s9p": "Podemos actualizar esta política periódicamente. Te notificaremos sobre cambios significativos mediante:",
  "s9li1": "Un aviso destacado en la plataforma",
  "s9li2": "Notificación por correo electrónico",
  "s9li3": "Actualización de la fecha \"Última actualización\" al inicio de este documento",
  "s10Title": "10. Contacto",
  "s10p": "Para preguntas sobre esta política de privacidad o el manejo de tus datos:",
  "emailLine": "<b>Email:</b> privacy@doapp.com",
  "dpoLine": "<b>Responsable de Protección de Datos:</b> dpo@doapp.com",
  "addressLine": "<b>Dirección:</b> Buenos Aires, Argentina",
  "s10note": "También puedes presentar una queja ante la Agencia de Acceso a la Información Pública (AAIP) de Argentina.",
  "commitment": "<b>Compromiso de privacidad:</b> En DOAPP valoramos tu privacidad y nos comprometemos a proteger tu información personal. Si tienes alguna pregunta o inquietud, no dudes en contactarnos.",
  "linkTerms": "Términos y Condiciones",
  "linkCookies": "Política de Cookies",
  "linkDisputes": "Resolución de Disputas",
};
