/**
 * Terms & Conditions — español copy. Single source for web and mobile.
 *
 * Web loads this through i18next (client/i18n/index.ts merges it into the
 * `termsPage` namespace); mobile imports it directly, since mobile has no i18n
 * runtime. The text previously lived twice — in client/i18n/locales/*.json and
 * hardcoded in mobile/app/legal/terms.tsx — which meant the two platforms could
 * silently drift apart on a legal document. Edit here and both follow.
 *
 * Keys are section-numbered: sNTitle / sNpM (paragraph) / sNliM (list item).
 */

export const termsEs: Record<string, string> = {
  "metaTitle": "Términos y Condiciones - DOAPP",
  "metaDescription": "Términos y condiciones generales de uso de la plataforma DOAPP",
  "back": "Volver",
  "home": "Inicio",
  "title": "Términos y Condiciones Generales de Uso",
  "lastUpdated": "Última actualización: 17 de Marzo de 2026",
  "intro1": "Los presentes Términos y Condiciones (en adelante, los \"Términos\") regulan el acceso y uso de la plataforma digital denominada DOAPP (en adelante, la \"Plataforma\"), por parte de cualquier persona humana o jurídica que se registre y/o utilice sus servicios (en adelante, el \"Usuario\").",
  "intro2": "La utilización de la Plataforma implica la aceptación plena y sin reservas de los presentes Términos, los cuales constituyen un contrato válido y vinculante conforme a los artículos 958 y concordantes del Código Civil y Comercial de la Nación.",
  "s1Title": "1. Identificación del Titular de la Plataforma",
  "s1p": "La Plataforma es operada por DOAPP, con domicilio legal en la República Argentina (en adelante, \"DOAPP\").",
  "s2Title": "2. Descripción del Servicio",
  "s2p": "DOAPP es una plataforma digital de intermediación tecnológica, bajo el modelo de marketplace y red social, que permite vincular:",
  "s2note": "DOAPP NO presta los servicios publicados, NO es empleador, NO actúa como parte del contrato de prestación de servicios, limitándose su rol a facilitar herramientas tecnológicas de contacto, gestión de pagos, custodia de fondos y mediación en disputas.",
  "s3Title": "3. Naturaleza Jurídica de la Relación",
  "s3p1": "3.1. Los Trabajadores se registran y actúan como prestadores independientes y autónomos, sin que exista relación laboral, societaria, de dependencia, mandato, agencia o franquicia con DOAPP.",
  "s3p2": "3.2. Cada contrato celebrado a través de la Plataforma se perfecciona exclusivamente entre Cliente y Trabajador, quienes asumen íntegramente los derechos y obligaciones emergentes del mismo.",
  "s3p3": "3.3. DOAPP no ejerce control técnico, disciplinario ni organizativo sobre los Trabajadores, limitándose a reglas de uso de la Plataforma.",
  "s4Title": "4. Registro de Usuarios",
  "s4p1": "4.1. El acceso a la Plataforma requiere registro previo y creación de una cuenta personal.",
  "s4p2": "4.2. El Usuario garantiza la veracidad, exactitud y actualización de los datos suministrados.",
  "s4p3": "4.3. DOAPP podrá requerir procesos de verificación de identidad (KYC), incluyendo validación de correo electrónico, teléfono, documento de identidad y datos fiscales, especialmente para membresías PRO y SUPER PRO.",
  "s4p4": "4.4. Alcance de la verificación. Al día de hoy DOAPP verifica únicamente la identidad de los Usuarios. Dicha verificación se realiza mediante la herramienta de un tercero especializado, Didit (didit.me), que analiza el documento de identidad presentado y realiza una prueba de vida mediante reconocimiento facial. A tal fin, el Usuario consiente que DOAPP transmita a dicho proveedor las imágenes de su documento y de su rostro, con la única finalidad de verificar su identidad y prevenir el fraude. El tratamiento de esos datos por parte del proveedor se rige además por sus propias políticas. DOAPP NO verifica matrículas profesionales, habilitaciones, títulos ni pólizas de seguro. Un Usuario puede declarar que posee una matrícula o un seguro y acompañar documentación respaldatoria: dicha documentación se conserva a título informativo y su exhibición en la Plataforma NO implica que DOAPP haya comprobado su autenticidad, vigencia ni validez ante el organismo o la aseguradora correspondiente.",
  "s4p5": "4.5. Es responsabilidad exclusiva del Usuario contratante verificar, por sus propios medios y ante los registros oficiales pertinentes, que el profesional cuente con la matrícula, habilitación o seguro que declara, especialmente en actividades reguladas. DOAPP informará oportunamente si en el futuro incorpora la verificación de estos datos contra fuentes oficiales.",
  "s5Title": "5. Categorías de Servicios",
  "s5p": "La Plataforma permite la publicación y contratación de servicios, entre otros:",
  "s5li1": "Limpieza",
  "s5li2": "Mudanzas",
  "s5li3": "Jardinería",
  "s5li4": "Construcción",
  "s5li5": "Tecnología",
  "s5li6": "Servicios profesionales varios",
  "s5note": "DOAPP no garantiza la idoneidad, calidad, resultado ni legalidad de los servicios ofrecidos.",
  "s6Title": "6. Sistema de Contratación",
  "s6p1": "6.1. El ciclo de contratación incluye: publicación, postulación, aceptación, pago, ejecución, confirmación por parte de un administrador de la plataforma y completado.",
  "s6p2": "6.2. La aceptación del Trabajador y del Cliente genera un contrato digital vinculante entre ambos.",
  "s6p3": "6.3. El sistema requiere confirmación bilateral de finalización para la liberación de fondos.",
  "s7Title": "7. Pagos, Comisiones y Escrow",
  "s7p1": "7.1. Los pagos se procesan a través de MercadoPago, aceptándose los medios habilitados por dicho proveedor.",
  "s7p2": "7.2. DOAPP actúa como custodio de fondos (escrow), reteniendo el dinero hasta la confirmación del servicio.",
  "s7p3": "7.3. DOAPP percibe una comisión por el uso de la Plataforma, conforme al plan del Usuario:",
  "thPlan": "Plan",
  "thCommission": "Comisión",
  "planProMonth": "PRO ($4.999/mes)",
  "planSuperProMonth": "SUPER PRO ($8.999/mes)",
  "s7p4": "7.4. Comisión mínima: para contratos inferiores a $8.000 ARS se aplicará una comisión fija de $1.000 ARS.",
  "s7p5": "7.5. La comisión de DOAPP no es reembolsable, incluso en casos de cancelación o disputa.",
  "s7p7": "7.7. Los Trabajadores serán notificados antes del inicio del trabajo, durante su ejecución y al momento de la liberación del pago. En caso de ausencia del Cliente conforme al punto 7.6, los Trabajadores recibirán aviso inmediato por email y notificación en la Plataforma.",
  "s8Title": "8. Membresías y Suscripciones",
  "s8p1": "8.1. DOAPP ofrece planes FREE, PRO y SUPER PRO, con renovación automática mensual.",
  "s8p2": "8.2. La cancelación no genera reintegro y los beneficios subsisten hasta el vencimiento del período abonado.",
  "s8p3": "8.3. DOAPP podrá modificar precios, notificando previamente al Usuario.",
  "s9Title": "9. Cancelaciones",
  "s9p1": "9.1. Cancelaciones previas a la aceptación por parte de un Administrador de la plataforma: devolución total.",
  "s9p2": "9.2. Cancelaciones hasta 24 horas antes del inicio: devolución del monto menos comisión, siempre y cuando la publicación no haya sido aceptada por un administrador de la plataforma.",
  "s9p3": "9.3. Cancelaciones tardías o durante la ejecución: distribución proporcional conforme lo establecido en la Plataforma, con retención de comisiones.",
  "s10Title": "10. Disputas y Mediación",
  "s10p1": "10.1. DOAPP actúa como mediador interno, sin carácter jurisdiccional.",
  "s10p2": "10.2. La apertura de una disputa congela los fondos hasta su resolución.",
  "s10p3": "10.3. Las decisiones del Administrador podrán consistir en liberación total, reembolso total, parcial o cierre sin acción. Para la toma de la resolución definitiva, se utilizará la información que voluntariamente remitieron las partes sobre las condiciones de contratación.",
  "s10p4": "10.4. La comisión de la Plataforma no se devuelve en ningún supuesto.",
  "s11Title": "11. Responsabilidad",
  "s11p1": "11.1. DOAPP no responde por:",
  "s11li1": "La calidad, ejecución o resultado de los servicios.",
  "s11li2": "Daños personales, materiales o patrimoniales derivados de la prestación.",
  "s11p2": "11.2. El Usuario exonera a DOAPP de cualquier reclamo derivado de su relación contractual con otros Usuarios.",
  "s12Title": "12. Impuestos y Facturación",
  "s12p1": "12.1. Los Trabajadores son responsables de emitir las facturas correspondientes y cumplir con sus obligaciones fiscales ante AFIP.",
  "s12p2": "12.2. DOAPP podrá emitir factura por el cobro de sus comisiones.",
  "s13Title": "13. Protección de Datos Personales",
  "s13p1": "13.1. DOAPP cumple con la Ley 25.326 de Protección de Datos Personales.",
  "s13p2": "13.2. Los datos bancarios y de identidad se almacenan de forma encriptada.",
  "s13p3": "13.3. El Usuario podrá ejercer los derechos de acceso, rectificación, supresión y oposición.",
  "s14Title": "14. Publicidad",
  "s14p": "DOAPP podrá ofrecer espacios publicitarios sujetos a disponibilidad, aprobación previa y pago anticipado.",
  "s15Title": "15. Sanciones",
  "s15p": "DOAPP podrá aplicar advertencias, suspensiones o cancelación definitiva de cuentas ante incumplimientos, fraude o uso indebido de la Plataforma.",
  "s16Title": "16. Modificaciones",
  "s16p": "DOAPP podrá modificar estos Términos, los cuales entrarán en vigencia desde su publicación.",
  "s17Title": "17. Ley Aplicable y Jurisdicción",
  "s17p": "Los presentes Términos se rigen por las leyes de la República Argentina. Para los consumidores, será competente el tribunal del domicilio del Usuario conforme Ley 24.240.",
  "s18Title": "18. Aceptación",
  "s18p": "El Usuario declara haber leído, comprendido y aceptado íntegramente los presentes Términos y Condiciones.",
  "acceptAndBack": "Acepto los términos, volver",
};
