/**
 * Terms & Conditions — español copy. Single source for web and mobile.
 *
 * Web loads this through i18next (client/i18n/index.ts merges it into the
 * `termsPage` namespace); mobile imports it directly, since mobile has no i18n
 * runtime. The text previously lived twice — in client/i18n/locales/*.json and
 * hardcoded in mobile/app/legal/terms.tsx — which meant the two platforms could
 * silently drift apart on a legal document. Edit here and both follow.
 *
 * Keys are section-numbered: sNTitle / sNpM (paragraph) / sNliM (list item).
 */

export const termsEs: Record<string, string> = {
  "metaTitle": "Términos y Condiciones - DOAPP",
  "metaDescription": "Términos y condiciones generales de uso de la plataforma DOAPP",
  "back": "Volver",
  "home": "Inicio",
  "title": "Términos y Condiciones Generales de Uso",
  "lastUpdated": "Última actualización: 17 de Marzo de 2026",
  "intro1": "Los presentes Términos y Condiciones (en adelante, los \"Términos\") regulan el acceso y uso de la plataforma digital denominada DOAPP (en adelante, la \"Plataforma\"), por parte de cualquier persona humana o jurídica que se registre y/o utilice sus servicios (en adelante, el \"Usuario\").",
  "intro2": "La utilización de la Plataforma implica la aceptación plena y sin reservas de los presentes Términos, los cuales constituyen un contrato válido y vinculante conforme a los artículos 958 y concordantes del Código Civil y Comercial de la Nación.",
  "s1Title": "1. Identificación del Titular de la Plataforma",
  "s1p": "La Plataforma es operada por DOAPP, con domicilio legal en la República Argentina (en adelante, \"DOAPP\").",
  "s2Title": "2. Descripción del Servicio",
  "s2p": "DOAPP es una plataforma digital de intermediación tecnológica, bajo el modelo de marketplace y red social, que permite vincular:",
  "s2li1": "<b>Clientes:</b> personas humanas o jurídicas que demandan servicios.",
  "s2li2": "<b>Trabajadores / Doers:</b> personas humanas que ofrecen servicios profesionales u oficios de manera independiente.",
  "s2note": "DOAPP NO presta los servicios publicados, NO es empleador, NO actúa como parte del contrato de prestación de servicios, limitándose su rol a facilitar herramientas tecnológicas de contacto, gestión de pagos, custodia de fondos y mediación en disputas.",
  "s3Title": "3. Naturaleza Jurídica de la Relación",
  "s3p1": "3.1. Los Trabajadores se registran y actúan como prestadores independientes y autónomos, sin que exista relación laboral, societaria, de dependencia, mandato, agencia o franquicia con DOAPP.",
  "s3p2": "3.2. Cada contrato celebrado a través de la Plataforma se perfecciona exclusivamente entre Cliente y Trabajador, quienes asumen íntegramente los derechos y obligaciones emergentes del mismo.",
  "s3p3": "3.3. DOAPP no ejerce control técnico, disciplinario ni organizativo sobre los Trabajadores, limitándose a reglas de uso de la Plataforma.",
  "s4Title": "4. Registro de Usuarios",
  "s4p1": "4.1. El acceso a la Plataforma requiere registro previo y creación de una cuenta personal.",
  "s4p2": "4.2. El Usuario garantiza la veracidad, exactitud y actualización de los datos suministrados.",
  "s4p3": "4.3. DOAPP podrá requerir procesos de verificación de identidad (KYC), incluyendo validación de correo electrónico, teléfono, documento de identidad y datos fiscales, especialmente para membresías PRO y SUPER PRO.",
  "s4p4": "4.4. Alcance de la verificación. Al día de hoy DOAPP verifica únicamente la identidad de los Usuarios. Dicha verificación se realiza mediante la herramienta de un tercero especializado, Didit (didit.me), que analiza el documento de identidad presentado y realiza una prueba de vida mediante reconocimiento facial. A tal fin, el Usuario consiente que DOAPP transmita a dicho proveedor las imágenes de su documento y de su rostro, con la única finalidad de verificar su identidad y prevenir el fraude. El tratamiento de esos datos por parte del proveedor se rige además por sus propias políticas. DOAPP NO verifica matrículas profesionales, habilitaciones, títulos ni pólizas de seguro. Un Usuario puede declarar que posee una matrícula o un seguro y acompañar documentación respaldatoria: dicha documentación se conserva a título informativo y su exhibición en la Plataforma NO implica que DOAPP haya comprobado su autenticidad, vigencia ni validez ante el organismo o la aseguradora correspondiente.",
  "s4p5": "4.5. Es responsabilidad exclusiva del Usuario contratante verificar, por sus propios medios y ante los registros oficiales pertinentes, que el profesional cuente con la matrícula, habilitación o seguro que declara, especialmente en actividades reguladas. DOAPP informará oportunamente si en el futuro incorpora la verificación de estos datos contra fuentes oficiales.",
  "s5Title": "5. Categorías de Servicios",
  "s5p": "La Plataforma permite la publicación y contratación de servicios, entre otros:",
  "s5li1": "Limpieza",
  "s5li2": "Mudanzas",
  "s5li3": "Jardinería",
  "s5li4": "Construcción",
  "s5li5": "Tecnología",
  "s5li6": "Servicios profesionales varios",
  "s5note": "DOAPP no garantiza la idoneidad, calidad, resultado ni legalidad de los servicios ofrecidos.",
  "s6Title": "6. Sistema de Contratación",
  "s6p1": "6.1. El ciclo de contratación incluye: publicación, postulación, aceptación, pago, ejecución, confirmación por parte de un administrador de la plataforma y completado.",
  "s6p2": "6.2. La aceptación del Trabajador y del Cliente genera un contrato digital vinculante entre ambos.",
  "s6p3": "6.3. El sistema requiere confirmación bilateral de finalización para la liberación de fondos.",
  "s6p4": "6.4. <b>El precio publicado es el precio del trabajo.</b> Cuando el Cliente publica indicando un monto, ése es el precio acordado y es el que se cobra, salvo que un Trabajador presente una cotización por un importe distinto y el Cliente decida aceptarla. Cuando el Cliente publica \"a cotizar\", no existe precio hasta que se acepta una cotización.",
  "s6p5": "6.5. <b>La aceptación de una cotización requiere el pago previo.</b> El Trabajador queda seleccionado y el contrato se genera únicamente después de que el pago se acredite. Si la cotización aceptada supera lo ya abonado en la publicación, el Cliente debe abonar la diferencia junto con la comisión correspondiente antes de que la selección tenga efecto. Mientras el pago no se acredite, la cotización permanece disponible y el Trabajador no queda comprometido.",
  "s6p6": "6.6. <b>Publicaciones sin cotización aceptada.</b> Las publicaciones \"a cotizar\" que no obtengan una cotización aceptada dentro de los 10 (diez) días hábiles desde su publicación o desde su última reanudación serán pausadas automáticamente. La pausa no cancela la publicación ni elimina las cotizaciones recibidas: el Cliente puede reanudarla en cualquier momento y el plazo se computa nuevamente desde la reanudación. <b>Las publicaciones cuyo precio fue abonado al publicarse no se pausan por este motivo</b>, y permanecen disponibles mientras el Cliente no las cancele.",
  "s7Title": "7. Pagos, Comisiones y Escrow",
  "s7p1": "7.1. Los pagos se procesan a través de MercadoPago, aceptándose los medios habilitados por dicho proveedor.",
  "s7p2": "7.2. DOAPP actúa como custodio de fondos (escrow), reteniendo el dinero hasta la confirmación del servicio.",
  "s7p3": "7.3. DOAPP percibe una comisión por el uso de la Plataforma, conforme al plan del Usuario:",
  "thPlan": "Plan",
  "thCommission": "Comisión",
  "planProMonth": "PRO ($4.999/mes)",
  "planSuperProMonth": "SUPER PRO ($8.999/mes)",
  "s7p4": "7.4. Comisión mínima: para contratos inferiores a $8.000 ARS se aplicará una comisión fija de $1.000 ARS.",
  "s7p5": "7.5. La comisión de DOAPP no es reembolsable, incluso en casos de cancelación o disputa.",
  "s7p6": "7.6. <b>Liberación automática por ausencia del Cliente:</b> Si un trabajo finaliza (fecha de vencimiento alcanzada) y el Cliente no confirma la recepción del servicio dentro de las 24 (veinticuatro) horas siguientes, con recordatorios previos, el pago retenido en custodia será liberado automáticamente a los Trabajadores asignados. La comisión de la Plataforma correspondiente al plan del Cliente se retiene en todos los casos. La liberación automática queda registrada como tal y no equivale a una conformidad expresa del Cliente, que conserva su derecho a reclamar dentro del plazo del artículo 10.7. Esta cláusula no aplica si existe una disputa activa sobre el contrato.",
  "s7p7": "7.7. Los Trabajadores serán notificados antes del inicio del trabajo, durante su ejecución y al momento de la liberación del pago. En caso de ausencia del Cliente conforme al punto 7.6, los Trabajadores recibirán aviso inmediato por email y notificación en la Plataforma.",
  "s7p8": "7.8. <b>Montos mínimos.</b> La Plataforma establece un monto mínimo de contratación y un monto mínimo de ampliación. Estos mínimos no son tarifas ni importes fijados discrecionalmente: la Plataforma los determina a partir del costo de procesamiento que cobra la pasarela de pago, del costo fijo que tiene cada contrato para la Plataforma —custodia de fondos, verificación de identidad y atención de disputas—, del tipo de cambio y de la comisión aplicable. Cuando alguno de esos valores cambia, los mínimos se recalculan en consecuencia. Los importes vigentes se informan siempre antes de publicar y antes de aceptar una cotización. El mínimo de contratación se verifica al aceptar una cotización, que es el momento en que existe un precio definitivo; una publicación \"a cotizar\" puede crearse sin precio.",
  "s7p9": "7.9. <b>Saldo a favor por cotización menor al precio publicado.</b> Si el Cliente abonó el precio publicado y luego acepta una cotización por un importe menor, la diferencia se acredita como saldo a favor dentro de la Plataforma. Ese saldo puede utilizarse sin costo alguno en cualquier publicación o contratación posterior. El Cliente también puede solicitar su transferencia a una cuenta bancaria propia; en ese caso, <b>el costo de procesamiento que cobra la pasarela de pago por la operación se descuenta del importe transferido</b>, dado que se trata de una devolución de dinero ya procesado y la Plataforma no percibe comisión alguna sobre esa diferencia. El importe del costo se informa antes de confirmar la solicitud. Si el Cliente no acepta ese descuento, el saldo permanece disponible en la Plataforma por tiempo indeterminado.",
  "s8Title": "8. Membresías y Suscripciones",
  "s8p1": "8.1. DOAPP ofrece planes FREE, PRO y SUPER PRO, con renovación automática mensual.",
  "s8p2": "8.2. La cancelación no genera reintegro y los beneficios subsisten hasta el vencimiento del período abonado.",
  "s8p3": "8.3. DOAPP podrá modificar precios, notificando previamente al Usuario.",
  "s9Title": "9. Cancelaciones",
  "s9p1": "9.1. Cancelaciones previas a la aceptación por parte de un Administrador de la plataforma: devolución total.",
  "s9p2": "9.2. Cancelaciones hasta 24 horas antes del inicio: devolución del monto menos comisión, siempre y cuando la publicación no haya sido aceptada por un administrador de la plataforma.",
  "s9p3": "9.3. Cancelaciones tardías o durante la ejecución: distribución proporcional conforme lo establecido en la Plataforma, con retención de comisiones.",
  "s9p4": "9.4. <b>Cancelación por parte del Trabajador de un contrato aceptado.</b> Cancelar un trabajo ya aceptado perjudica al Cliente y a la Plataforma. Por ello, las cancelaciones del Trabajador dentro de un período de 90 (noventa) días tienen consecuencias graduales: la primera genera un aviso; la segunda hace visible en el perfil del Trabajador, durante 90 días, una marca que indica que canceló trabajos aceptados; la tercera o siguientes suspenden la posibilidad de postularse a nuevos trabajos durante 14 (catorce) días. Los contratos en curso no se ven afectados por la suspensión. Avisar oportunamente que no se podrá realizar el trabajo, a través de la función prevista en la Plataforma, se considera igualmente una cancelación a estos efectos, pero permite al Cliente decidir cómo disponer de su dinero sin demoras.",
  "s10Title": "10. Disputas y Mediación",
  "s10p1": "10.1. DOAPP actúa como mediador interno, sin carácter jurisdiccional.",
  "s10p2": "10.2. La apertura de una disputa congela los fondos hasta su resolución.",
  "s10p3": "10.3. Las decisiones del Administrador podrán consistir en liberación total, reembolso total, parcial o cierre sin acción. Para la toma de la resolución definitiva, se utilizará la información que voluntariamente remitieron las partes sobre las condiciones de contratación.",
  "s10p4": "10.4. La comisión de la Plataforma no se devuelve en ningún supuesto.",
  "s10p5": "10.5. <b>Detalles obligatorios y detalles deseables:</b> Al crear o ampliar un contrato, las partes acuerdan <b>detalles obligatorios</b>: condiciones concretas y verificables que definen qué se considera el trabajo cumplido (por ejemplo, «la canilla no debe dejar cinta de teflón visible saliendo de la rosca»). Sólo esos detalles pueden fundar una disputa. Los <b>detalles deseables</b> son preferencias que las partes pueden dejar asentadas para orientar el trabajo, pero <b>no fundan una disputa ni pueden originarla</b>.",
  "s10p6": "10.6. DOAPP no interviene ni resuelve reclamos basados en condiciones que no fueron acordadas como detalles obligatorios antes de comenzar el trabajo o antes de aprobarse la ampliación. Acordar bien los detalles obligatorios es responsabilidad de las partes; la Plataforma provee la herramienta para registrarlos.",
  "s10p7": "10.7. <b>Plazo para reclamar:</b> La disputa puede iniciarse mientras el contrato está en curso y hasta 7 (siete) días corridos después de su finalización. Pasado ese plazo, el contrato se considera aceptado sin observaciones. La apertura de una disputa dentro de ese plazo no retiene fondos ya liberados, pero habilita la mediación de DOAPP y queda registrada.",
  "s10p8": "10.8. <b>Contracargos:</b> Si el Cliente desconoce un pago ante su banco o emisor de tarjeta (contracargo) en lugar de utilizar el sistema de disputas de la Plataforma, se compromete a notificarlo previamente a DOAPP. El Cliente será responsable por el monto reclamado cuando el servicio haya sido efectivamente prestado, y DOAPP podrá reclamarle el importe, suspender su cuenta y retener saldos disponibles hasta la resolución. DOAPP presentará ante el emisor la evidencia del contrato: confirmaciones de ambas partes, código de emparejamiento, historial de mensajes y fechas.",
  "s10p9": "10.9. El uso del sistema interno de disputas es la vía prevista para reclamar. Iniciar un contracargo sin haberlo intentado no exime al Usuario de las obligaciones asumidas en estos Términos.",
  "s10p10": "10.10. <b>Falta de respuesta en una disputa.</b> Cada parte tiene 7 (siete) días corridos para responder al último mensaje de la otra parte dentro de una disputa. Abrir la disputa cuenta como primer mensaje. Si una parte no responde en ese plazo, la disputa se resuelve automáticamente a favor de la parte que respondió última: si quien no respondió es el Trabajador, el dinero retenido se devuelve al Cliente; si quien no respondió es el Cliente, el pago se libera al Trabajador. La Plataforma envía un aviso a la parte en silencio 2 (dos) días antes del vencimiento. Los mensajes de la administración de la Plataforma no interrumpen este plazo. La comisión de la Plataforma no se reembolsa en ningún caso, conforme al punto 7.5.",
  "s11Title": "11. Responsabilidad",
  "s11p1": "11.1. DOAPP no responde por:",
  "s11li1": "La calidad, ejecución o resultado de los servicios.",
  "s11li2": "Daños personales, materiales o patrimoniales derivados de la prestación.",
  "s11p2": "11.2. El Usuario exonera a DOAPP de cualquier reclamo derivado de su relación contractual con otros Usuarios.",
  "s12Title": "12. Impuestos y Facturación",
  "s12p1": "12.1. Los Trabajadores son responsables de emitir las facturas correspondientes y cumplir con sus obligaciones fiscales ante AFIP.",
  "s12p2": "12.2. DOAPP podrá emitir factura por el cobro de sus comisiones.",
  "s13Title": "13. Protección de Datos Personales",
  "s13p1": "13.1. DOAPP cumple con la Ley 25.326 de Protección de Datos Personales.",
  "s13p2": "13.2. Los datos bancarios y de identidad se almacenan de forma encriptada.",
  "s13p3": "13.3. El Usuario podrá ejercer los derechos de acceso, rectificación, supresión y oposición.",
  "s14Title": "14. Publicidad",
  "s14p": "DOAPP podrá ofrecer espacios publicitarios sujetos a disponibilidad, aprobación previa y pago anticipado.",
  "s15Title": "15. Sanciones",
  "s15p": "DOAPP podrá aplicar advertencias, suspensiones o cancelación definitiva de cuentas ante incumplimientos, fraude o uso indebido de la Plataforma.",
  "s16Title": "16. Modificaciones",
  "s16p": "DOAPP podrá modificar estos Términos, los cuales entrarán en vigencia desde su publicación.",
  "s17Title": "17. Ley Aplicable y Jurisdicción",
  "s17p": "Los presentes Términos se rigen por las leyes de la República Argentina. Para los consumidores, será competente el tribunal del domicilio del Usuario conforme Ley 24.240.",
  "s18Title": "18. Aceptación",
  "s18p": "El Usuario declara haber leído, comprendido y aceptado íntegramente los presentes Términos y Condiciones.",
  "importantNote": "<b>Nota importante:</b> Al registrarte y utilizar DOAPP, confirmas que has leído, entendido y aceptado estos Términos y Condiciones en su totalidad.",
  "acceptAndBack": "Acepto los términos, volver",
};
